### ISSUE TITLE
Asking for permission

### ISSUE THREAD

**Issue by youlha1** [shoaibhassan0/Google_Password_Stealer#1]
First and foremost, I'd like to commend you on your exceptional work. Your project stands out, especially given that it was crafted entirely in pure C. I've come across numerous projects in the past, but none have showcased such dedication to the language as yours has.
I'm reaching out to respectfully seek your permission to utilize your project as a foundational element for creating my own project. This would involve modifying its code, renaming the project, and extending its functionalities. My goal is to adapt and develop versions tailored for other operating systems, specifically Linux. It's important to note that my derivative work will not be intended for commercial gain; instead, it will serve as a portfolio piece.
Despite the modifications I'll be implementing, I am committed to giving you due credit. I plan to acknowledge you and specify that I've used your project under the link "https://github.com/shoaibhassan0/Google_Password_Stealer" as a foundational reference.
I genuinely value your contribution and hope to have your consent to proceed.

**Comment by shoaibhassan0** [comment]
@yo-aiv1 Thank you for your kind words and for expressing your interest in utilizing my project for your own work. I'm glad you find value in it.

I appreciate your commitment to giving due credit and outlining your plans for modification and extension. If you are comfortable, I suggest officially forking the repository on GitHub. This way, you can have a distinct copy of the project, and it will make it easier for others to track your modifications.

Feel free to proceed with the fork, and I look forward to seeing your adaptation. If you have any further questions or need assistance with the forking process, don't hesitate to ask.

Best regards,
Shoaib Hassan

**Comment by youlha1** [comment]
I really have no idea, how license work, if you can just tell me what i cannot do, and if what i asked for is okay such as editing and changing name and functionality, and that the project won't be used for commercial purposes.
Do you have whatsapp, discord or telegram, or somewhere where i can text you?

**Comment by shoaibhassan0** [comment]
Give me your email i will send you my whatsapp contact.

**Comment by shoaibhassan0** [comment]
Here is telegram contanct https://t.me/shoaibhassana
